### ISSUE TITLE
Automatic builds

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#161]
Hi all (@Vocaluxe, @Flamefire, @brunzel, @flokuep, @stsundermann, @derivator),

as we are not having nightly builds for a quite long time I started working on a new solution with better github integration. Additionally I restructured our dependencies to make it easier for new people to build Vocaluxe form the scratch (and to support automatic builds easily :wink: )
Now its nearly done: Windows builds are running successfully on a branch in my fork.

**The questions are now:**
- Do you/we want the build system to be integrated in Vocaluxe/Vocaluxe?
- Who is actively working on Vocaluxe and has the control over the Vocaluxe organization on github and the website.

---
## More details please...
- Automatic builds for
  - Every tag
  - Special branches (automatic tag creation and movement) e.g. develop -> Nightly
  - Pull request (build only, no releases)
- Release-zips are uploaded to github releases
- Pull request on github are flagged whether the build was successful or not
- Using github api for creating version tag, so lightweight clones are sufficient
- Using nuget for all dependencies
  - Just clone and click `Rebuild All` the rest is done automatically
  - gstreamer dlls will be automatically downloaded during build if not installed on the system
  - Theme files are also downloaded and not longer in the repo
  - all dependencies are now in the `libs` folder -> less files in the root directory
- Automatic version_set switch for the Vocaluxe.sln (no up/downgrading anymore)
- Vocaluxe is portable again
### ToDo
- [x] Create Accounts at [appveyor.com](https://appveyor.com) and [travis](https://travis-ci.org) for Vocaluxe
- [x] Using a shared password manager with shared database for those accounts?
- [x] Change config to use `Vocaluxe/Vocaluxe` and develop as nightly branch
- [x] Create `access tokens` (for tag moving and releases) and `webhooks` on github for the build services (which account -> new vocaluxe_builder github account?)
- [ ] Finish Linux build
### Windows build
- [x] Use a [powershell script](https://gist.github.com/lukeIam/b97a9dd17a945ac59c8b) to generate the "git-describe" version tag with the github api 
- [x] Complete windows build is working using [appveyor.com](https://appveyor.com):
  [![appveyor](https://cloud.githubusercontent.com/assets/5115160/10488721/52053818-729a-11e5-8a13-94990c980afa.png)](https://ci.appveyor.com/project/lukeIam/vocaluxe)
  [![github releases](https://cloud.githubusercontent.com/assets/5115160/10488779/9c7d29dc-729a-11e5-8c9e-e9d5033101a3.png)](https://github.com/lukeIam/Vocaluxe/releases)
### Linux build
- [x] Mono build using [travis](https://travis-ci.org)
- [x] Deploy
- [x] Building manged dependencies (ffmpeg under ubuntu 12.04 LTS)
- [x] Rebuild git-describe with github api for getting version tag

**Comment by derivator** [comment]
I'm definitely in favour of automatic builds and you've been doing great work, :+1:! I hope I'll soon have time again to help finish getting linux building automatically.

I'm still somewhat uncomfortable with Nuget and its lack of hashing/validation though... Would [git-lfs](https://git-lfs.github.com/) maybe work? Seems a bit simpler, though I haven't used it myself yet. Hope it's not too rude of me to offer counter-suggestions this late when you've done a lot of work with Nuget already, I only became aware of git-lfs this week...
Either way, if we're going to use either of these or even a third option, it might be worth to consider *rewriting history* using some repo cleaning tool to purge the dependencies from the repo entirely and greatly reduce its size... Of course that shouldn't be done lightly as it would change every single commit hash...

Finally, and I realize this is a giant nit-pick... before we merge this, could you squash some of the commits? There are a lot of commits like
https://github.com/lukeIam/Vocaluxe/commit/4cfecb1020a8a0b260faad393a727088284e3064 that are just one-line changes with no commit descriptions, that don't help me understand what's being done. All they do is clutter up the commit log. Maybe I'm a bit obsessive here, but I think a commit log should be beautiful and concise :)

Anyway, great work, I support it.

**Comment by lukeIam** [comment]
@derivator Thanks for your feedback!

> I'm still somewhat uncomfortable with Nuget and its lack of hashing/validation though...

With this point I have to concede that it would be nice to have some nuget build in sining mechanism.
But as Microsoft is focusing nuget as deployment for .NET (they started distributing parts of the BCL over it) and it is pretty well integrated in VisualStudio it is getting some kind of standard for .NET .
I'll make the distribution progress as transparent as possible:
```
team owned git-repo with the dependencies
                          |
                          V
team owned myget.org account which crawls the git-repo and publishes the nuget feed
                          |
                          V
nuget client that consumes the feed
(I've disabled the other default sources to prevent an injection)
```

> Would git-lfs maybe work? Seems a bit simpler, though I haven't used it myself yet.

I also havn't used git-lfs yet, but as far as I know it couldn't replace nuget directly.
nuget does more than simple file coping-  it also:
* injects the dependencies into the project configuration
* injects the switches for choosing the right dependency corresponding to the current target (Windows/Linux and x86/x64)

> Either way, if we're going to use either of these or even a third option, it might be worth to consider rewriting history using some repo cleaning tool to purge the dependencies from the repo entirely and greatly reduce its size... Of course that shouldn't be done lightly as it would change every single commit hash...

On the one hand it would force everybody to update his local clone and all forks (so maybe a lot of cherry picking - merge will not longer work?). On the other hand our repo has grown quite big (~630MB).
Anyway if we want to do that should definitely triple check if everything worked fine before pushing it (and have a backup somewhere).
Maybe [that](https://rtyley.github.io/bfg-repo-cleaner/) tool makes it a bit easier.

> Maybe I'm a bit obsessive here, but I think a commit log should be beautiful and concise :)

I totally agree! And normally I do write descriptive log messages. But in this case I had to figure out the right configuration of the ci services. And to only way to change something and test it is to push a commit - so I had to do this very often...
As the general system was working and I only had to fix specific bugs I started writing log messages again.

> before we merge this, could you squash some of the commits? 

Of cause :wink: (I'll squash them if the decision is positive)

> Anyway, great work, I support it.

Thanks :smiley:

**Comment by VocaluxeBuildBot** [comment]
Windows build system is now ready to go live #170

**Comment by lukeIam** [comment]
Windows build system is now ready to go live #170

**Comment by lukeIam** [comment]
Windows build is working and Linux build seems to be a bigger thing.

I suggest to move this point out of Milestone [0.3 Release](https://github.com/Vocaluxe/Vocaluxe/milestones/0.3%20Release)

**Comment by flokuep** [comment]
:+1:

**Comment by lukeIam** [comment]
I created a .NET 4 version of the gitdescribe PowerShell script:
https://github.com/lukeIam/githubDescribe
(Should work with Mono under Linux)

**Comment by lukeIam** [comment]
@derivator 

Got it compiling on travis (Ubuntu 12.04.5 LTS):  
https://travis-ci.org/lukeIam/Vocaluxe/builds/189576098

But compiling ffmpeg takes about 20min in every build.

Still to do:
- [ ] test if the binaries are running (I'm still missing some runtime dependencies :unamused: )
- [ ] cache all required ffmpeg files
- [ ] do we want to have artifacts?  
how do we pack a release for linux so that it will support the main linux distributions (runtime dependencies)?
- [ ] reconfigure travis artifact publishing

But for now I had enough of fighting with ubuntu dependencies  :grimacing:

**Comment by lukeIam** [comment]
> cache all required ffmpeg files

I tried out to download pre-build ffmpeg files (created with the same script on Ubuntu 12.04).
It compiles without errors und is much faster:  
https://travis-ci.org/lukeIam/Vocaluxe/builds/189661718

**Comment by marwin89** [comment]
hi @flokuep can this issue be closed? or is it still relevant for linux build?

- #673

**Comment by flokuep** [comment]
Just as a reference for some hints, so yeah. Can be closed.
